### ISSUE TITLE
issue running in windows

### ISSUE THREAD

**Issue by jeffa17** [N0MoreSecr3ts/wraith#56]
Hi ,

can someone help me with the below error. i have downloaded the code and complied in my windows machine.

Below is the error when i run the compiled exe with token. 

![image](https://user-images.githubusercontent.com/70229832/91211253-1c718380-e72c-11ea-905a-60b3d5dbbce7.png)

Thanks
Jeff

**Comment by mattyjones** [comment]
@jeffa17 This is due to the concurrency/threading being unhappy. Most likely there was a group/repo/? not pulled through either via command line flag or the config file.

Can you please share the exact command and any configuration file you used. Looking at the screenshot unless you used a config file there are no targets such as people, repos, path, etc declared. `wraith.exe --help` should provide you more details on the flags that are required. If nothing is listed as required please open a bug and we will look at getting that pushed into a future version to prevent panics like this.

**Comment by jeffa17** [comment]
Hi @mattyjones ,

Thank you for quick response. Below is the command i'm using and i have only modified github api token value in config.yml file. below is the screenshot

wraith.exe scanGithub --github-api-token <<actual token>>

![image](https://user-images.githubusercontent.com/70229832/91254706-ad724a00-e780-11ea-8f5d-e66121095927.png)
)

Also could you please help me where should we configure URL in case of GitHub enterprise

Thanks,
Jeff

**Comment by mattyjones** [comment]
@jeffa17 Concerning GHE. There will be GHE support coming. I already know how to implement it but it is different than github.com. The URL for obvious reasons is different but the client is also different. Top of my head I don't remember what it is but it was something silly.

Currently, the focus is on stability and testing, I am not implementing any new features till I am comfortable and can prove this is working as it should. That said, I will accept pull requests for new features, I just don't have the bandwidth to write them. Unfortunately, when we started looking at the code and started writing tests and debug info we uncovered a lot of fairly gnarly bugs. Many have been fixed but a few are still outstanding.

Can you confirm that you pulled the **0.0.5** release or built from Master? This should work. You will also need to pull down the signatures, if you look at the screenshot you are not loading any. Take a look at the updated [readme](https://github.com/N0MoreSecr3ts/wraith/blob/master/README.md) in Master. 

Coming down the line in a few weeks, for linux any is packaging with rpm's and debs. I have no idea yet on windows but I think maybe a zipfile is still the best way to go. Chocolatey is a viable alternative but I know more about astrophysics than windows packaging.

**Comment by jeffa17** [comment]
Hi @mattyjones ,

Thank you for the detailed explanation. sorry for my naive doubts. i'm new to coding and even compiling from git. 

i pulled the code from 0.0.5 release and compiled on my machine. now i have copied the signature file into same directory and updated the signature part in config file like below and still facing same error

signature-file: default.yml

windows uses '\' as path separator. do i need to give full path in signature-file : C:\Go\bin\default.yml? (this is also giving same error)

![image](https://user-images.githubusercontent.com/70229832/91325996-71230600-e7e1-11ea-9ebb-09ea1920cd26.png)

i'll try pulling master release today and update you the result.

**Comment by mattyjones** [comment]
@jeffa17 That is a good point, I honestly have not tested on windows myself but gitrob which this is based on, did have windows support I believe. There very well could be path issues. I have an open task to spin up a win 7/10 box to play with and figure out any nuances, I just don't have the bandwidth and there are functional bugs affecting multiple platforms that need to be addressed first.

**Comment by mattyjones** [comment]
This is the [code](https://github.com/N0MoreSecr3ts/wraith/blob/master/core/session.go#L204-L219) setting the signatures
```go
	var curSig []Signature
	var combinedSig []Signature
	SignaturesFile := v.GetString("signature-file")
	if SignaturesFile != "" {
		Signatures := strings.Split(SignaturesFile, ",") // TODO make slice

		for _, f := range Signatures {
			f = strings.TrimSpace(f)
			h := SetHomeDir(f)
			if PathExists(h, s) {
				curSig = LoadSignatures(h, s.MatchLevel, s)
				combinedSig = append(combinedSig, curSig...)
			}
		}
	} // TODO need to catch this error here
	Signatures = combinedSig
}
```

I am willing to bet it is how the home directory is being picked up. Dropping it into the root of wraith won't work either checkout out the code here for the [default values](https://github.com/N0MoreSecr3ts/wraith/blob/master/core/session.go#L60-L61).
```go
var DefaultValues = map[string]interface{}{
	"bind-address":     "127.0.0.1",
	"bind-port":        9393,
	"commit-depth":     0,
	"config-file":      "$HOME/.wraith/config.yaml",
	"debug":            false,
	"github-targets":   "",
	"github-api-token": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXVZabcd",
	"gitlab-targets":   "",
	"gitlab-api-token": "0123456789ABCDEFGHIJ",
	"ignore-extension": "",
	"ignore-path":      "",
	"in-mem-clone":     false,
	"max-file-size":    50,
	"num-threads":      0,
	"local-dirs":       nil,
	"local-files":      nil,
	"scan-forks":       true,
	"scan-tests":       false,
	"scan-type":        "",
	"silent":           false,
	"csv":              false,
	"json":             false,
	"match-level":      3,
	"signature-file":   "$HOME/.wraith/signatures/default.yml",
	"signature-path":   "$HOME/.wraith/signatures/",
	"signature-url":    "",
	"scan-dir":         "",
	"scan-file":        "",
	"hide-secrets":     false,
}
```

My thought for getting this up and running quickly would be to use the `--signature-file` flag and set it to the full path that way we don't have expansion issues. Once you can confirm that works we can troubleshoot what or why not expansion does not work. If it does not work my thought would be to check to see if `$HOME` is in your environment and if Windows supports `~`.

**Comment by jeffa17** [comment]
Hi @mattyjones 

Thanks for your suggestion. it is working after configuring token,signature file and target in command like below

![image](https://user-images.githubusercontent.com/70229832/91331923-1392b780-e7e9-11ea-90b1-9d167ccf00f5.png)

i'll be waiting for your release which support Github enterprise and gitlab offline release.

Thank you so much for guiding.

-Jeff

**Comment by mattyjones** [comment]
@jeffa17 What do you mean by gitlab offline. This release will allow the scanning of local repos and paths. Did I miss something in gitlab functionality?

**Comment by jeffa17** [comment]
Hi @mattyjones ,

we have one gitlab deployment (gitlab community edition) hosted internally just like GHE. just wanted to know if this supports the scanning of standalone gitlab(not gitlab.com) in future. even for this ,i might need to configure internal URL somewhere in code which i'm not sure. :(

**Comment by mattyjones** [comment]
@codeEmitter ^ does your code support this? Thoughts?
